name: BenchmarkOps with GPU

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 실행
  workflow_dispatch:

jobs:
  benchmark_ops:
    runs-on: self-hosted  # GPU 서버에서 실행
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install datasets torch torchvision transformers tqdm json

    - name: Check GPU Availability
      run: python -c "import torch; print('CUDA Available:', torch.cuda.is_available())"

    - name: Run Data Pipeline with GPU
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python pipeline.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add merged_test_data.json
        git commit -m "Auto-update benchmark data" || echo "No changes to commit"
        git push
